version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: serval
      POSTGRES_DB: serval
    ports:
      - "5432:5432"
    volumes:
      - ./serval.sql:/docker-entrypoint-initdb.d/serval.sql
