"""create donuts table

Revision ID: c0f21a834493
Revises: 
Create Date: 2024-06-04 14:24:18.037746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0f21a834493"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donuts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("donut", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_donuts")),
        sa.UniqueConstraint("donut", name=op.f("uq_donuts_donut")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("donuts")
    # ### end Alembic commands ###
