"""Donut migration

Revision ID: e47d0387df51
Revises: 
Create Date: 2024-06-06 16:42:01.897462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47d0387df51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donuts', sa.Column('donut', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_donuts_donut'), 'donuts', ['donut'])
    op.drop_column('donuts', 'donut_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donuts', sa.Column('donut_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_donuts_donut'), 'donuts', type_='unique')
    op.drop_column('donuts', 'donut')
    # ### end Alembic commands ###
